#!/usr/bin/env bash
#
# Fetch SMHasher3, register river5 as a hash, build, and run.
#
# What this script does:
#   1. Clones SMHasher3 (fwojcik/smhasher3) into third_party/_smhasher3/
#      if not already present. Re-running won't re-clone.
#   2. Copies the river5 C sources (incl. xxhash for the fallback)
#      into smhasher3/hashes/river5/ so SMHasher3's CMake build can
#      compile them as part of its single test binary.
#   3. Writes hashes/river5.cpp — the registration shim that exposes
#      our hash to SMHasher3's REGISTER_HASH/REGISTER_FAMILY macros.
#   4. Patches hashes/Hashsrc.cmake to list our new sources.
#   5. Configures + builds SMHasher3 with CMake.
#   6. Runs the requested test (default: Sanity, fast). Pass --all to
#      run the full battery — that takes ~30 minutes.
#
# Caveats:
#   - First run computes a "verification value" SMHasher3 expects.
#     The first run will print a warning that verification_LE is
#     wrong; copy the value SMHasher3 prints into the cpp file
#     under hashes/river5.cpp (verification_LE / verification_BE)
#     and re-run.
#   - If SMHasher3 upstream changes its registration API, this
#     script's generated cpp file will need updating. The
#     registration template is small (~40 lines) — easy to fix.
#
# Usage:
#   scripts/run_smhasher3.sh             # quick Sanity test
#   scripts/run_smhasher3.sh --all       # full battery (~30 min)
#   scripts/run_smhasher3.sh --test=X    # specific SMHasher3 test
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SMH_DIR="$ROOT/third_party/_smhasher3"
SMH_REPO="https://gitlab.com/fwojcik/smhasher3.git"

TEST_ARG="--test=Sanity"
if [[ "${1:-}" == "--all" ]]; then
    TEST_ARG=""  # SMHasher3 with no --test runs all tests
elif [[ "${1:-}" == --test=* ]]; then
    TEST_ARG="$1"
fi

# --- 1. Clone if needed ---
if [[ ! -d "$SMH_DIR" ]]; then
    echo "[1/6] cloning SMHasher3 into $SMH_DIR..."
    git clone --depth 1 "$SMH_REPO" "$SMH_DIR"
else
    echo "[1/6] using existing SMHasher3 checkout: $SMH_DIR"
fi

# --- 2. Copy river5 sources ---
echo "[2/6] copying river5 sources into $SMH_DIR/hashes/river5/"
mkdir -p "$SMH_DIR/hashes/river5"
cp "$ROOT/csrc/river5.c"          "$SMH_DIR/hashes/river5/"
cp "$ROOT/csrc/river5_aesni.c"    "$SMH_DIR/hashes/river5/"
cp "$ROOT/csrc/river5_stub.c"     "$SMH_DIR/hashes/river5/"
cp "$ROOT/csrc/river5_internal.h" "$SMH_DIR/hashes/river5/"
cp "$ROOT/include/river5.h"       "$SMH_DIR/hashes/river5/"
cp "$ROOT/third_party/xxhash/xxhash.c" "$SMH_DIR/hashes/river5/"
cp "$ROOT/third_party/xxhash/xxhash.h" "$SMH_DIR/hashes/river5/"

# --- 3. Write the registration shim ---
echo "[3/6] writing hashes/river5.cpp registration shim"
cat > "$SMH_DIR/hashes/river5.cpp" << 'EOF'
/*
 * river5 — SMHasher3 registration shim.
 * Auto-generated by river5/scripts/run_smhasher3.sh.
 */
#include "Platform.h"
#include "Hashlib.h"

extern "C" {
#include "river5/river5.h"
}

#include <cstring>

/*
 * SMHasher3 passes a 64-bit seed_t. Our hash takes a 32-byte key.
 * We tile the seed across the key area so different seeds produce
 * meaningfully different hash families.
 */
static inline void expand_seed(uint8_t key[RIVER5_SEED_BYTES], seed_t seed) {
    uint64_t s = static_cast<uint64_t>(seed);
    for (size_t i = 0; i < RIVER5_SEED_BYTES; i += sizeof(s)) {
        std::memcpy(key + i, &s, sizeof(s));
    }
}

template <bool bswap>
static void RIVER5_128_Hash(const void * in, const size_t len,
                             const seed_t seed, void * out) {
    uint8_t key[RIVER5_SEED_BYTES];
    expand_seed(key, seed);

    uint8_t buf[RIVER5_HASH_BYTES];
    river5_hash(in, len, key, buf);

    /* Our impl emits little-endian bytes. bswap=true means SMHasher3
     * wants big-endian — reverse the 16-byte output. */
    if (bswap) {
        for (int i = 0; i < RIVER5_HASH_BYTES; ++i) {
            static_cast<uint8_t *>(out)[i] = buf[RIVER5_HASH_BYTES - 1 - i];
        }
    } else {
        std::memcpy(out, buf, RIVER5_HASH_BYTES);
    }
}

REGISTER_FAMILY(river5,
   $.src_url    = "https://github.com/mickfixesjunk/river5",
   $.src_status = HashFamilyInfo::SRC_ACTIVE
 );

REGISTER_HASH(RIVER5_128,
   $.desc            = "river5: 8-lane AES-NI hash for file dedup",
   $.impl            = "aesni",
   $.hash_flags      =
         FLAG_HASH_AES_BASED,
   $.impl_flags      =
         0,
   $.bits            = 128,
   /* Both verification values are intentionally zero on the first
    * build. SMHasher3 will print the correct values on first run;
    * paste them in here and rebuild for clean output. */
   $.verification_LE = 0x0,
   $.verification_BE = 0x0,
   $.hashfn_native   = RIVER5_128_Hash<false>,
   $.hashfn_bswap    = RIVER5_128_Hash<true>
 );
EOF

# --- 4. Patch Hashsrc.cmake (idempotent) ---
HASHSRC="$SMH_DIR/hashes/Hashsrc.cmake"
if ! grep -q 'river5.cpp' "$HASHSRC"; then
    echo "[4/6] patching $HASHSRC"
    # Insert our sources right before the closing paren.
    python3 - "$HASHSRC" << 'PYEOF'
import sys
path = sys.argv[1]
with open(path) as f:
    src = f.read()
inject = (
    "  hashes/river5.cpp\n"
    "  hashes/river5/river5.c\n"
    "  hashes/river5/river5_aesni.c\n"
    "  hashes/river5/river5_stub.c\n"
    "  hashes/river5/xxhash.c\n"
)
# find the last ')' and insert before it
idx = src.rfind(')')
if idx < 0:
    sys.exit("could not find closing paren in " + path)
src = src[:idx] + inject + src[idx:]
with open(path, 'w') as f:
    f.write(src)
PYEOF
else
    echo "[4/6] $HASHSRC already lists river5.cpp — skipping"
fi

# --- 5. Configure + build ---
echo "[5/6] configuring CMake build..."
mkdir -p "$SMH_DIR/build"
( cd "$SMH_DIR/build" && cmake .. -DCMAKE_BUILD_TYPE=Release >/dev/null )
echo "      building..."
( cd "$SMH_DIR/build" && cmake --build . -j )

# --- 6. Run ---
echo "[6/6] running SMHasher3..."
if [[ -n "$TEST_ARG" ]]; then
    "$SMH_DIR/build/SMHasher3" "$TEST_ARG" RIVER5-128
else
    "$SMH_DIR/build/SMHasher3" RIVER5-128
fi
